[[database]]
name = "database_name"
host = "127.0.0.1"
bucket = "backup_site"
cnf = "config.cnf"

    [[database.vno]]
    name = "daily"
    path = "{month}/{day}/dump.sql.gz"

    [[database.vno]]
    name = "monthly"
    path = "{year}/{month}/{day}/dump.sql.gz"
